services:
  springboot-app:
    image: habit-tracker-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cu4r1obtq21c73dsvo40-a.oregon-postgres.render.com:5432/habit_tracker_db_2tex
      - SPRING_DATASOURCE_USERNAME=habit_tracker_db_2tex_user
      - SPRING_DATASOURCE_PASSWORD=lZdIE3an839Vv2vxGYET2jdgirPPSRUL
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: habit_tracker_db_2tex
      POSTGRES_USER: habit_tracker_db_2tex_user
      POSTGRES_PASSWORD: lZdIE3an839Vv2vxGYET2jdgirPPSRUL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
